# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=todo_db

# SQL Server - authentification SQL (mixte)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AgentIA_BourseDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=InvestIA2024!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# Serveur
server.port=8080

# JWT
jwt.secret=investai_secret_key_pfe_2024_very_long_secret
jwt.expiration=86400000

# Debug Security
logging.level.org.springframework.security=DEBUG

# n8n Agent webhook (update with your actual webhook ID)
n8n.webhook.url=http://localhost:5678/webhook/investia-chat

# Mail (Gmail SMTP) - remplacez par vos vraies credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abdessayedmanar@gmail.com
spring.mail.password=vaok bido fojf cvie
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# URL du frontend (pour le lien de reset dans l'email)
app.frontend.url=http://localhost:4200
